# Generated by Django 4.0.6 on 2022-07-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kind',
            field=models.CharField(choices=[('ŻYCIE', 'ŻYCIE'), ('YOGA', 'YOGA'), ('PILATES', 'PILATES'), ('GŁOS', 'GŁOS')], max_length=32),
        ),
    ]
